# -*- mode: ruby -*-
# vi: set ft=ruby :

# Customize VM resources
VM_CPUS = "4"
VM_MEMORY = "2048" # MB
VM_NAME = "OrionU16"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.provider :virtualbox do |vb|
    vb.customize [ "modifyvm", :id,
    "--memory", VM_MEMORY,
    "--name", VM_NAME,
    "--nicspeed1", 1000000,
    "--nicspeed2", 1000000,
    "--ioapic", "on",
    "--cpus", VM_CPUS ]
    end

    # SSH
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true

    config.vm.provision :shell, path: "../install_dependencies.sh"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
